### ISSUE TITLE
Oh-My-ZSH

### ISSUE THREAD

**Issue by wellcome2017** [tonylambiris/dotfiles#2]
Dear, after setup I'm having this error
Do you know how to solve it?

distro: manjaro/gnome
versão zsh: zsh 5.4.2 (x86_64-unknown-linux-gnu)

![captura de tela de 2017-11-10 21-35-42](https://user-images.githubusercontent.com/33560873/32684094-231e618a-c65f-11e7-9fe8-5415b6bfe294.png)

**Comment by tonylambiris** [comment]
@wellcome2017 I would venture a guess that you have pu aliased elsewhere... can you replace line 427 with the following and let me know if it works alright?
```code
alias pu='() { pushd $1 &> /dev/null; dirs -v; }'
```

**Comment by wellcome2017** [comment]
Do you say replace this line?
the error continues

Congratulations on your work, sorry for my English.
![captura de tela de 2017-11-11 11-41-53](https://user-images.githubusercontent.com/33560873/32690485-5176cc58-c6d6-11e7-81b9-445d5708d965.png)

**Comment by wellcome2017** [comment]
Dear I did as you request, the error changes to the next line.
![captura de tela de 2017-11-11 12-09-17](https://user-images.githubusercontent.com/33560873/32690700-7e98a406-c6d9-11e7-89c5-0b4f9ff9516d.png)

**Comment by wellcome2017** [comment]
Dear, I have made the following changes based on your information
would this be the correct behavior of the terminal?
![captura de tela de 2017-11-11 12-29-07](https://user-images.githubusercontent.com/33560873/32690852-56c9fb48-c6dc-11e7-9464-79734aed3f9f.png)

**Comment by wellcome2017** [comment]
Dear, could you help me and solve the problem of returning the symbol?

see attached photo.

![error](https://user-images.githubusercontent.com/33560873/33338182-04545ee6-d454-11e7-8a76-1857ed1572b4.jpg)

**Comment by tonylambiris** [comment]
This theme is configured to utilize https://github.com/ryanoasis/nerd-fonts

If you're on arch linux these packages exist in the AUR:

- nerd-fonts-complete
- nerd-fonts-complete-mono-glyphs

**Comment by wellcome2017** [comment]
Excuses, but the problem persists.

Already with nerd-fonts-competa installed

I uninstalled and injected nerd-fonts-complete-mono-glyphs the problem and the same

Anything else you can do?

use arch linux + gnome

![image](https://user-images.githubusercontent.com/33560873/33437249-19b63e44-d5c6-11e7-9db4-4c92e07d2589.png)

**Comment by tonylambiris** [comment]
I'm on gnome and arch as well, I don't have any issues as far as I can tell.

I would try doing the following:
`$ rm -rf ~/.zplug ; source ~/.zshrc`

Sometimes things get cached or "stuck".
