### ISSUE TITLE
Show bunch of lines at terminal startup

### ISSUE THREAD

**Issue by nheolinkin** [tonylambiris/dotfiles#3]
After installation finishes, I reopen terminal and it show like this:
![deepinscreenshot_20171115144414](https://user-images.githubusercontent.com/27943508/32824486-c527ee58-ca13-11e7-9d7d-867ab119ff47.png)

These are lines that I changed from your config:

> alias pu='() { pushd $1 &> /dev/null; dirs -v; }'
alias po() { popd &> /dev/null; dirs -v; }

And commented bypassed plugins
> zplug "plugins/dnf",       from:oh-my-zsh, if:"which dnf"
> zplug "plugins/go",        from:oh-my-zsh, if:"which go"
> zplug "plugins/golang",    from:oh-my-zsh, if:"which go"
> zplug "plugins/nmap",      from:oh-my-zsh, if:"which nmap"
> zplug "plugins/tmux",      from:oh-my-zsh, if:"which tmux"
>

**Comment by tonylambiris** [comment]
I've figured out a much better way for checking commands, I just haven't gotten around to back-porting these changes, ie:

```sh
# Supports oh-my-zsh plugins and the like
if [[ $OSTYPE = (linux)* ]]; then
	zplug "plugins/archlinux",     from:oh-my-zsh, if:"(( $+commands[pacman] ))"
	zplug "plugins/dnf",           from:oh-my-zsh, if:"(( $+commands[dnf] ))"
	zplug "plugins/mock",          from:oh-my-zsh, if:"(( $+commands[mock] ))"
fi
```
