### ISSUE TITLE
Oh my zsh 

### ISSUE THREAD

**Issue by RunningYoung** [tonylambiris/dotfiles#5]
![image](https://user-images.githubusercontent.com/7145734/33475098-1e9c9578-d6b8-11e7-937c-b2936e865774.png)

**Comment by RunningYoung** [comment]
what's problem? can you help me ?

**Comment by ecarradal** [comment]
I have the same problem :C

**Comment by dtluther** [comment]
Same. We just copy your zshrc file into our .zshrc file, right?

**Comment by RunningYoung** [comment]
https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X .

**Comment by fedemengo** [comment]
Did it solve the problem for you?
I installed the fonts but some icons still don't display properly.

![screen shot 2018-02-11 at 11 48 50](https://user-images.githubusercontent.com/19249682/36072564-cc75f2e2-0f21-11e8-8233-530e199f2406.png)

**Comment by RunningYoung** [comment]
Disable System Integrity Protection
Reboot your mac and hold CMD+R after the startup chime.

Launch Terminal.app from the Utilities menu once booted into System Recovery and run:

csrutil disable; reboot
Edit Plist
Once rebooted back into normal mode, use Xcode.app to open and edit the plist file after first copying it to ~/Desktop:

cp /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/Resources/DefaultFontFallbacks.plist ~/Desktop
open -a Xcode.app ~/Desktop/DefaultFontFallbacks.plist
In the plist editor, expand "monospace" then click the + icon to add a new row and type in Pomodoro. Do this three more times for FontAwesome, Octicons, and Icomoon until the plist looks like:

image

Overwrite DefaultFontFallbacks.plist
Make a backup of the original DefaultFontFallbacks.plist:

cp /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/Resources/DefaultFontFallbacks.plist ~/DefaultFontFallbacks.plist.bak
Close Xcode.app and move the file back into place, overwriting the original:

sudo mv ~/Desktop/DefaultFontFallbacks.plist /System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreText.framework/Resources/DefaultFontFallbacks.plist
Re-Enable System Integrity Protection
Now reboot into recovery mode again (CMD+R) and re-enable System Integrity Protection:

csrutil enable; reboot
Tested with iTerm2 Build 3.0.5

**Comment by tonylambiris** [comment]
This theme only supports nerd fonts: https://github.com/ryanoasis/nerd-fonts
