### ISSUE TITLE
Last prompt slightly off

### ISSUE THREAD

**Issue by talon-i-am** [tonylambiris/dotfiles#6]
Wondering what causes the last prompt to always be slightly off. It seems to happen with the ones that are not rounded as well. They never seem to line up perfectly. Any ideas?

![image](https://user-images.githubusercontent.com/13376907/34541704-86e4219e-f096-11e7-8298-43aef93191cb.png)

**Comment by talon-i-am** [comment]
I was able to remedy it by increasing the vertical character spacing in the iTerm2 text settings. 

![image](https://user-images.githubusercontent.com/13376907/34573501-a2465bd2-f131-11e7-9a1a-06e1a0df7a52.png)

**Comment by dtluther** [comment]
Is there a better way to do this?

**Comment by christiawaneko** [comment]
thanks t-hughes, it's better when i try what you do
just open iterm -> preferences -> tab Profile -> tab Text -> click Change Font , 
and slide vertical character spacing

**Comment by tonylambiris** [comment]
Yeah it has to do with the font and it's spacing -- you just need to hunt around for one that does the job. For nerd fonts, sometimes it's worth trying one's specifically marked as mono fonts.

For example I use the mononoki regular font, but the mononoki mono regular font renders better for my terminals.
