### ISSUE TITLE
showing symbols instead of words

### ISSUE THREAD

**Issue by maths-lover** [tonylambiris/dotfiles#7]
Hello I have a problem here,
My terminal(Manjaro kde) started showing symbols when i type some certain set of letter (like fi, etc.)

![problem](https://user-images.githubusercontent.com/25811797/39158715-458be4bc-477f-11e8-9635-e2d94fe73b73.gif)

**Comment by tonylambiris** [comment]
Have you tried running a `zplug update`?

Also what font are you using

**Comment by maths-lover** [comment]
I tried but still same thing.

The font I'm using is ShureTechMono Nerd Font Mono

**Comment by maths-lover** [comment]
I solved the issue, I just installed everything again.
