### ISSUE TITLE
Python virtualenvwrapper

### ISSUE THREAD

**Issue by kudokun07** [tonylambiris/dotfiles#8]
How i can display env's name? Tks

**Comment by tonylambiris** [comment]
You have to add `virtualenv` to either `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`, depending where you want it.

As an example I added it to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` so now when I activate a virtualenv I get the following in my prompt:

![gnome-shell-screenshot-e0pgnz](https://user-images.githubusercontent.com/14058972/43898477-f75758c6-9bac-11e8-84a2-499f6c0fa690.png)
